class Order():
    """
    Duża litera- restauracja
    mała litera- punkt odbiory z restauracji o tej samej literze (tylko dużej)
    pierwsze miejsce w krotce liczba jeśli parzysta to punkt Odbioru jeśli nieparzysta punkt dostawy
    """
    A = (0, 'A')
    a = (1, 'a')
    B = (2, 'B')
    b = (3, 'b')
    C = (4, 'C')
    c = (5, 'c')
    D = (6, 'D')
    d = (7, 'd')
    E = (8, 'E')
    e = (9, 'e')
    F = (10, 'F')
    f = (11, 'f')
    G = (12, 'G')
    g = (13, 'g')
    H = (14, 'H')
    h = (15, 'h')
    I = (16, 'I')
    i = (17, 'i')
    J = (18, 'J')
    j = (19, 'j')
    K = (20, 'K')
    k = (21, 'k')
    L = (22, 'L')
    l = (23, 'l')
    M = (24, 'M')
    m = (25, 'm')
    N = (26, 'N')
    n = (27, 'n')
